version: "3.1"

services:
  redis:
    container_name: echo-redis
    build:
      context: ./
      dockerfile: etc/docker/redis.Dockerfile
    image: echo-redis
    ports:
      - 6379:6379
    networks:
      - private
    logging:
      options:
        max-size: 50m

networks:
  private:
    driver: bridge
