version: "3.1"

services:
  redis:
    container_name: echo-redis
    build:
      context: ./
      dockerfile: etc/docker/redis.Dockerfile
    logging:
      options:
        max-size: "50m"

  app:
    container_name: echo-app
    depends_on:
      - redis
    links:
      - "redis:database"
    build:
      context: ./
      dockerfile: etc/docker/app.Dockerfile
    image: echo
    env_file:
      - .env
    ports:
      - "3000:3000"
    logging:
      options:
        max-size: "50m"
